apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: 237249058690.dkr.ecr.ap-northeast-2.amazonaws.com/demo-frontend
  newName: 237249058690.dkr.ecr.ap-northeast-2.amazonaws.com/demo-frontend
  newTag: c86e9491
resources:
- ../../base
patchesStrategicMerge:
- front-deployment-patch.yaml
- front-service-patch.yaml
